server:
  port: 7001
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: cloud-eureka-server7001
  client:
    #不向注册中心注册自己
    register-with-eureka: false
    #不检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: cloud-eureka-server7001